### ISSUE TITLE
Hey Mark

### ISSUE THREAD

**Issue by blabz2007** [blitz-research/blitz-world#1]
What are you brewing up here you sly man?

**Comment by blitz-research** [comment]
Hi,

Nothing too underhand, promise! This is (some of) the source to the 3d engine behind the skirmish test (which apparently needs it's server rebooted):

https://blitzresearch.itch.io/skirmish

I've decided to make it publicly available because it makes life easier for me (I wanted to have it 'backed up' on github but don't weanna mess around with private repos) and I honestly can't see any point in keeping the code private any more! 

There are no huge trade secrets or clever algorithms or anything particularly clever in there that would be to my 'commercial advantage' to obfuscate or hide, but there are I think a TON of useful like tips and trips and hacks that could be of use to someone other poor soul out there trying to stumble through the increasingly ugly and complex landscape of c++ game development out there.

I may rename it to something like 'simple game framework' soon, but I do still plan to write a 'blitz-world' app in it too so that's what it's called for now.

I'm also in the process of getting it working on PC and adding OpenXR/WebXR support so it'll probably be updated in random sized chunks at random times for a while yet.

Bye!
Mark
